---
title: "Creating Employee Persona's with K-Means Cluster Analysis"
description: |
  Experimenting with TidyClust to generate clusters of employees using dempgraphic data. This information could then be used to create employee persona's to inform HR activities intended to improve the employee experience. 
author:
  - name: Adam D McKinnon
    url: https://adam-d-mckinnon.com/
date: "`r Sys.Date()`"
categories:
  - Tidymodels
  - TidyClust
  - HR
  - Machine Learning
  - Employee Personas
  - R
output: 
  distill::distill_article:
    df_print: paged
    code_folding: true
    self_contained: false
    date_prefix: true # adds date for sorting
    toc: true
    toc_depth: 3
    highlight: rstudio
    highlight_downlit: true
    draft: true
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "##",
  out.width = "100%",
  out.height = "100%",
  dpi = 300,
  code_folding = TRUE,
  R.options = list(width = 100))

```




```{r libraries}

# data
library(peopleanalyticsdata)

# data manipulation
library(tidyverse)

# modelling
library(tidymodels)
library(tidyclust)
library(embed)

# visualising
library(Rtsne)
library(plotly)


data("managers", package = "peopleanalyticsdata")

rownames(managers) <- managers$employee_id

managers_df <- managers %>% 
    dplyr::select(-employee_id)

```


```{r}

managers_rec <- recipe(~ ., data = managers_df) %>% 
    step_dummy(all_nominal_predictors()) %>% 
    step_zv(all_predictors()) %>% 
    step_normalize(all_numeric_predictors()) %>% 
    step_pca(all_numeric_predictors(), threshold = 0.9)

managers_rec

```

```{r}

kmeans_spec <- k_means(num_clusters = tune()) %>% 
    set_engine("ClusterR")

kmeans_spec

```

```{r}

kmeans_wf <- workflow(
    managers_rec,
    kmeans_spec
)

kmeans_wf

```

```{r}

clust_num_grid <- grid_regular(num_clusters(),
                               levels = 10) # currently cannot tune for more than 10 clusters

```



```{r}

set.seed(519)
manager_bootstraps <- bootstraps(managers, times = 10)

tune_res <- tune_cluster(
    kmeans_wf,
    resamples = manager_bootstraps,
    grid = clust_num_grid,
    control = control_grid(save_pred = TRUE, extract = identity),
    metrics = cluster_metric_set(sse_within_total, sse_total, sse_ratio)
)

tune_res

```


```{r}

res_metrics <- collect_metrics(tune_res)



# not necessary, but interesting to note
res_metrics %>%
  filter(.metric == "sse_within_total") %>%
  ggplot(aes(x = num_clusters, y = mean)) +
  geom_point() +
  geom_line() +
  theme_minimal() +
  ylab("mean WSS/TSS ratio, over 5 folds") +
  xlab("Number of clusters") +
  scale_x_continuous(breaks = 1:10)



num_clusters <- select_best(tune_res) %>% pull(num_clusters)


```



```{r}


final_kmeans_spec <- k_means(num_clusters = 7) %>%
  set_engine("ClusterR")

final_kmeans_wf <- workflow(managers_rec, final_kmeans_spec)
final_kmeans_fit <- fit(final_kmeans_wf, data = managers)


personas_df <- 
    managers_df %>% 
    bind_cols(extract_cluster_assignment(final_kmeans_fit))
    

persona_coordinates_tbl <- bake((managers_rec %>% prep()), new_data = NULL) 


```



```{r visualise_clusters}

tsne_obj <- Rtsne::Rtsne(persona_coordinates_tbl)


personas_df <- personas_df %>% 
    rename(Cluster = ".cluster")
    mutate(
        description = stringr::str_glue("{Cluster}
        
                                        Performance Group: {performance_group}
                                        Tenure: {yrs_employed} years
                                        Test Score: {test_score}
                                        Group Size: {group_size}
                                        
                                        Flight Risk: {concern_flag}
                                        Burnout Risk: {high_hours_flag}
                                        Reduced Schedule: {reduced_schedule}
                                        
                                        Mobile: {mobile_flag}
                                        No. of Costumers: {customers}
                                        No. Of Transfers: {transfers}
                                        
                                        Location: {city}")
        
        )
    
    




tsne_tbl <- tsne_obj$Y %>% 
    tibble::as_tibble() %>% 
    dplyr::rename("X" = V1, "Y" = V2) %>% 
    dplyr::bind_cols(personas_df) 



g <- tsne_tbl %>%
    ggplot2::ggplot(aes(x = X, y = Y, colour = Cluster, text = description)) +
    geom_point()


plotly::ggplotly(g, tooltip = "text")

```


